// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieDBMinimalAPI.Data;

#nullable disable

namespace MovieDBMinimalAPI.Migrations
{
    [DbContext(typeof(DbApplicationContext))]
    partial class DbApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieDBMinimalAPI.Models.Movie", b =>
                {
                    b.Property<string>("imdbID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Awards")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxOffice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DVD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metascore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Production")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Released")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Runtime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imdbRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imdbVotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("imdbID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            imdbID = "tt0111161",
                            Actors = "Tim Robbins, Morgan Freeman, Bob Gunton",
                            Awards = "Nominated for 7 Oscars. 21 wins & 37 nominations.",
                            BoxOffice = "$28,767,189",
                            Country = "USA",
                            DVD = "21 Dec 1999",
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            Language = "English",
                            Metascore = "80",
                            MyRating = "8.8",
                            Plot = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Poster = "https://m.media-amazon.com/images/M/MV5B..._V1_SX300.jpg",
                            Production = "Columbia Pictures",
                            Rated = "R",
                            Released = "14 Oct 1994",
                            Response = "True",
                            Runtime = "142 min",
                            Title = "The Shawshank Redemption",
                            Type = "movie",
                            Website = "N/A",
                            Writer = "Stephen King, Frank Darabont",
                            Year = "1994",
                            imdbRating = "9.3",
                            imdbVotes = "2,840,490"
                        },
                        new
                        {
                            imdbID = "tt1375666",
                            Actors = "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
                            Awards = "Won 4 Oscars. 159 wins & 220 nominations.",
                            BoxOffice = "$292,576,195",
                            Country = "USA, UK",
                            DVD = "07 Dec 2010",
                            Director = "Christopher Nolan",
                            Genre = "Action, Adventure, Sci-Fi",
                            Language = "English, Japanese, French",
                            Metascore = "74",
                            MyRating = "8.5",
                            Plot = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            Poster = "https://m.media-amazon.com/images/M/MV5B..._V1_SX300.jpg",
                            Production = "Warner Bros. Pictures",
                            Rated = "PG-13",
                            Released = "16 Jul 2010",
                            Response = "True",
                            Runtime = "148 min",
                            Title = "Inception",
                            Type = "movie",
                            Website = "N/A",
                            Writer = "Christopher Nolan",
                            Year = "2010",
                            imdbRating = "8.8",
                            imdbVotes = "2,525,487"
                        },
                        new
                        {
                            imdbID = "tt0068646",
                            Actors = "Marlon Brando, Al Pacino, James Caan",
                            Awards = "Won 3 Oscars. 31 wins & 30 nominations.",
                            BoxOffice = "$134,966,411",
                            Country = "USA",
                            DVD = "09 Oct 2001",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime, Drama",
                            Language = "English, Italian, Latin",
                            Metascore = "100",
                            MyRating = "9.0",
                            Plot = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Poster = "https://m.media-amazon.com/images/M/MV5B..._V1_SX300.jpg",
                            Production = "Paramount Pictures",
                            Rated = "R",
                            Released = "24 Mar 1972",
                            Response = "True",
                            Runtime = "175 min",
                            Title = "The Godfather",
                            Type = "movie",
                            Website = "N/A",
                            Writer = "Mario Puzo, Francis Ford Coppola",
                            Year = "1972",
                            imdbRating = "9.2",
                            imdbVotes = "1,987,149"
                        });
                });

            modelBuilder.Entity("MovieDBMinimalAPI.Models.RatedMovie", b =>
                {
                    b.Property<string>("RatingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RatingId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("RatedMovies");

                    b.HasData(
                        new
                        {
                            RatingId = "rating1-user1-movie1",
                            MovieId = "tt0111161",
                            Rating = 9,
                            UserId = "user1-guid-abc"
                        },
                        new
                        {
                            RatingId = "rating2-user2-movie2",
                            MovieId = "tt1375666",
                            Rating = 8,
                            UserId = "user2-guid-xyz"
                        },
                        new
                        {
                            RatingId = "rating3-user1-movie3",
                            MovieId = "tt0068646",
                            Rating = 10,
                            UserId = "user1-guid-abc"
                        });
                });

            modelBuilder.Entity("MovieDBMinimalAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DateRegisteredAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "user1-guid-abc",
                            DateRegisteredAt = new DateOnly(2025, 4, 29),
                            Email = "alice@example.com"
                        },
                        new
                        {
                            Id = "user2-guid-xyz",
                            DateRegisteredAt = new DateOnly(2025, 5, 14),
                            Email = "bob@example.com"
                        });
                });

            modelBuilder.Entity("MovieDBMinimalAPI.Models.WatchlistMovie", b =>
                {
                    b.Property<string>("WatchlistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WatchlistId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchlistMovies");

                    b.HasData(
                        new
                        {
                            WatchlistId = "watchlist1-user1-movie2",
                            MovieId = "tt1375666",
                            UserId = "user1-guid-abc"
                        },
                        new
                        {
                            WatchlistId = "watchlist2-user2-movie1",
                            MovieId = "tt0111161",
                            UserId = "user2-guid-xyz"
                        });
                });

            modelBuilder.Entity("MovieDBMinimalAPI.Models.RatedMovie", b =>
                {
                    b.HasOne("MovieDBMinimalAPI.Models.Movie", "movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieDBMinimalAPI.Models.User", "User")
                        .WithMany("RatedMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("MovieDBMinimalAPI.Models.WatchlistMovie", b =>
                {
                    b.HasOne("MovieDBMinimalAPI.Models.Movie", "movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieDBMinimalAPI.Models.User", "User")
                        .WithMany("WatchlistMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("MovieDBMinimalAPI.Models.User", b =>
                {
                    b.Navigation("RatedMovies");

                    b.Navigation("WatchlistMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
